### ISSUE TITLE
Quoting mistake

### ISSUE THREAD

**Issue by DisDes** [MicrosoftDocs/xamarin-docs.de-de#41]
Hello, i think there is a mistake in the fist XAML-Quote on this page:

xmlns:controls="clr-namespace:MyCompany.Controls;assembly="MyCompany.Controls"

there are three Quoting-Signs

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3a849344-bfe7-89eb-3949-10591484a2cf
* Version Independent ID: 8be4b6ea-3cd8-8d74-58db-b07dcdf78ab6
* Content: [Benutzerdefinierte XAML-Namespace Schemas in xamarin. Forms - Xamarin](https://docs.microsoft.com/de-de/xamarin/xamarin-forms/xaml/custom-namespace-schemas#feedback)
* Content Source: [docs/xamarin-forms/xaml/custom-namespace-schemas.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/xamarin-forms/xaml/custom-namespace-schemas.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by srvbpigh** [comment]
Hello, @DisDes
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/xamarin-docs #2739](https://github.com/MicrosoftDocs/xamarin-docs/issues/2739) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @DisDes, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/2739. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
